= Building a Documentation Library with Maven and Asciidoctor
:ci.file: ci.file

The https://github.com/ricklarsen/ddf[Distributed Data Framework (DDF)] is an enterprise scale open-source project I worked on through several overhauls to migrate to a docs-as-code approach. The documentation is part of the build, ensuring version alignment and simultaneous release schedule. DDF is primarily built with [Apache Maven] and so the steps in the build process are defined in a pom.xml file.

Another consideration I worked with is that other projects downstream build upon DDF and would like to inherit the documentation content, rebrand it, and possibly add additional content.

== Maven Overview

samples from pom.xml
plugins:

. `<maven-dependency-plugin>` This plugin retrieves any content from upstream projects. As this is the foundational project, it does not apply here. Here is an example of it in a downstream project, fetching this content: https://github.com/ricklarsen/alliance/blob/master/distribution/docs/pom.xml#L135[Retrieve upstream content].
. `<maven-resources-plugin>` copies all of the content, images, scripts, and configuration files to the target directory. During this process, the text files are filtered to replace placeholders with the configured values.
. `<jbake-maven-plugin>` takes the filtered content pages and applies freemarker tempates to determine the order of the documents.
.. The asciidoc files (`.adoc`) have assigned `type`, `order` and `parent` properties in their headers that determine placement within larger sections.
+
.Asciidoctor header example, see https://github.com/ricklarsen/ddf/blob/master/distribution/docs/src/main/resources/content/_managing/_configuring/http-port.adoc[complete file] for context
[source,asciidoc]
....
:title: Configuring HTTP(S) Ports
:type: configuration
:status: published
:parent: Configuring Federation
:summary: Configure HTTP(S) Ports.
:order: 01
....
+
.. The freemarker templates (`*.ftl`) iterate on the `type` properties to determine the document placement. Types are defined in the `jbake.properties` file.
+
.jbake.properties excerpt, see https://github.com/ricklarsen/ddf/blob/master/distribution/docs/src/main/resources/jbake.properties[complete file] for context
[source]
....
output.extension=.adoc
template.documentation.file=documentation.ftl
template.introduction.file=overview.ftl
template.coreConcept.file=overview.ftl
template.subCoreConcept.file=overview.ftl
template.quickStart.file=quickstart.ftl
....
+
.. The `order` property of each `adoc` file sorts the sections and `parent` property matches subsections to their larger placement. The templates can also adjust the outline level of a subsection within the document. I use a nested loop to get a three-level outline structure.
+
.Freemarker (`*.ftl`) example, see https://github.com/ricklarsen/ddf/blob/master/distribution/docs/src/main/resources/templates/configuring.ftl[complete file] for context
[source,xml]
....
<#list configuringIntros?sort_by("order") as ci>
<#if (ci.status == "published")>

\include::${ci.file}[leveloffset=+1]

<#list configurations?sort_by("order") as configuration>
<#if (configuration.parent == ci.title)>

\include::${configuration.file}[leveloffset=+2]

<#if (configuration.title == "Connecting to Sources")>

<#include "sources.ftl">
</#if>
<#list subConfigurations?sort_by("order") as subConfiguration>
<#if (subConfiguration.parent == configuration.title)>

\include::${subConfiguration.file}[leveloffset=+3]

</#if>
</#list>
</#if>
</#list>
</#if>
</#list>
....
+
. `<asciidoctor-maven-plugin>` compiles the newly-created asciidoc content into the final, publishable form.
.. `HTML` pages are run by default, `PDF` generation takes extra time, so I made it optional in a development environment by creating a `<profile>` for PDF output.
. `<maven-assembly>` files package the raw adocs, and completed versions in zip files for deployment.
+
.asciidocs.xml excerpt, see https://github.com/ricklarsen/ddf/blob/master/distribution/docs/src/assembly/asciidocs.xml[complete file] for context
[source,xml]
....
<fileSet>
    <fileMode>0644</fileMode>
    <directoryMode>0755</directoryMode>
    <directory>src/main/resources/content</directory>
    <includes>
        <include>**</include>
    </includes>
    <outputDirectory></outputDirectory>
</fileSet>
....
+
. `<build-helper-maven-plugin>` deploys the published HTML and PDF files to the server for end-users to view.
+
.pom.xml Excerpt, see [complete file] for context
[source,xml]
....
<artifact>
    <file>${project.build.directory}/docs/html/documentation.html</file>
    <type>html</type>
    <classifier>documentation</classifier>
</artifact>
....
